name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'  # Or another version that matches your local environment
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -X -B package --file pom.xml  # Enable debug logging with -X
